/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdSpecsSpecIdRouteImport } from './routes/projects.$projectId.specs.$specId'
import { Route as ProjectsProjectIdSpecsSpecIdDiffRouteImport } from './routes/projects.$projectId.specs.$specId.diff'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSpecsSpecIdRoute =
  ProjectsProjectIdSpecsSpecIdRouteImport.update({
    id: '/specs/$specId',
    path: '/specs/$specId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSpecsSpecIdDiffRoute =
  ProjectsProjectIdSpecsSpecIdDiffRouteImport.update({
    id: '/diff',
    path: '/diff',
    getParentRoute: () => ProjectsProjectIdSpecsSpecIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/specs/$specId': typeof ProjectsProjectIdSpecsSpecIdRouteWithChildren
  '/projects/$projectId/specs/$specId/diff': typeof ProjectsProjectIdSpecsSpecIdDiffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/specs/$specId': typeof ProjectsProjectIdSpecsSpecIdRouteWithChildren
  '/projects/$projectId/specs/$specId/diff': typeof ProjectsProjectIdSpecsSpecIdDiffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/specs/$specId': typeof ProjectsProjectIdSpecsSpecIdRouteWithChildren
  '/projects/$projectId/specs/$specId/diff': typeof ProjectsProjectIdSpecsSpecIdDiffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/users'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/specs/$specId'
    | '/projects/$projectId/specs/$specId/diff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/users'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/specs/$specId'
    | '/projects/$projectId/specs/$specId/diff'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/users'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/specs/$specId'
    | '/projects/$projectId/specs/$specId/diff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UsersRoute: typeof UsersRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/specs/$specId': {
      id: '/projects/$projectId/specs/$specId'
      path: '/specs/$specId'
      fullPath: '/projects/$projectId/specs/$specId'
      preLoaderRoute: typeof ProjectsProjectIdSpecsSpecIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/specs/$specId/diff': {
      id: '/projects/$projectId/specs/$specId/diff'
      path: '/diff'
      fullPath: '/projects/$projectId/specs/$specId/diff'
      preLoaderRoute: typeof ProjectsProjectIdSpecsSpecIdDiffRouteImport
      parentRoute: typeof ProjectsProjectIdSpecsSpecIdRoute
    }
  }
}

interface ProjectsProjectIdSpecsSpecIdRouteChildren {
  ProjectsProjectIdSpecsSpecIdDiffRoute: typeof ProjectsProjectIdSpecsSpecIdDiffRoute
}

const ProjectsProjectIdSpecsSpecIdRouteChildren: ProjectsProjectIdSpecsSpecIdRouteChildren =
  {
    ProjectsProjectIdSpecsSpecIdDiffRoute:
      ProjectsProjectIdSpecsSpecIdDiffRoute,
  }

const ProjectsProjectIdSpecsSpecIdRouteWithChildren =
  ProjectsProjectIdSpecsSpecIdRoute._addFileChildren(
    ProjectsProjectIdSpecsSpecIdRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdSpecsSpecIdRoute: typeof ProjectsProjectIdSpecsSpecIdRouteWithChildren
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdSpecsSpecIdRoute:
    ProjectsProjectIdSpecsSpecIdRouteWithChildren,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UsersRoute: UsersRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
